var GAME_LEVELS = [
  ["  x                                                      v                   x  ",
   "  x                                                    v                     x  ",
   "  x                                                                          x  ",
   "  x       v                                                                  x  ",
   "  x                                                                o      c  x  ",
   "  x                                                                o         x  ",
   "  x                                                               xxx        x  ",
   "  x                                                xx      xx    xx!xx       x  ",
   "  x                                 o o      xx                  x!!!x       x  ",
   "  x                                                              xx!xx    o  x  ",
   "  x                                xxxxx                           v         x  ",
   "  x                                                                       o  x  ",
   "  x                        o o               o                               x  ",
   "  x                                                                       o  x  ",
   "  x                       xxxxx                                              x  ",
   "  x            i    xxx                                                   o  x  ",
   "  x  @                                                            xxxxx      x  ",
   "  xxxxxxxxxxxxxxxx                xxxxxxxx      xxxxxx     xxxxxxxx   xx  x  x  ",
   "                 x                x      x      x    x     x           x!!!!!x  ",
   "                 x!!!!!!!!!!!!!!!!x      x!!!!!!x    x!!!!!x           x!!!!!x  ",
   "                 x!!!!!!!!!!!!!!!!x      x!!!!!!x    x!!!!!x           x!!!!!x  ",
   "                 xxxxxxxxxxxxxxxxxx      xxxxxxxx    xxxxxxx           xxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "x!!xxxxxxx!xxxxxxxxxxx!xx!xxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x  ",
   " v!       v           v  v                           v                                        x!x  ",
   "  v                                                                                  o o o    x!x  ",
   "                                                                                      o o    xx!x  ",
   "                                                                                       o    xx!!x  ",
   "                                                                               xxxxxxxxxxxxxx!!!x  ",
   "                                                                              xx!!!!!!!!!!!!!!!!x  ",
   "                                                                      xx     xx!!!!!!!!!!!!!!!!!x  ",
   "                                                                o            x!!!!xxxxxxxxxxxxxxx  ",
   "                                 o                             xxx            v  v              x  ",
   "                                o                                                        y      x  ",
   "                o              xxxx              xx                                             x  ",
   "                 o             x  x                                                     xxx     x  ",
   "               xxxx           ox  x      xxx                        xxx                         x  ",
   "              xx  xx          xx  xx                                                        c   x  ",
   "     @       xx    xx         x    xx                                              xxx          x  ",
   "    xxx      x      x        xx     xx                  xxxxxxx              x                  x  ",
   "    x x      x      x        x       x                 xx     x                                 x  ",
   "    x x      x      x       xx       x                 x      x      xxxxx                      x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!xxx      x!!!!!!x   xx                     x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!x        x!!!!!!x    x                     x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!x        x!!!!!!x    x                     x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!x        x!!!!!!x    x!!!!!!!!!!!!!!!xx    x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!x        x!!!!!!x    x!!!!!!!!!!!!!!!!xx o x  ",
   "!!!!x x!!!!!!x      x!!!!!!!x        x!!!!!!!!!!!!!!!x        x!!!!!!x    x!!!!!!!!!!!!!!!!!xxxxx  "],
   [" x!                                                       ",
    " x!                                           c           ",
    " x!                         o                           o ",
    " x!=                        o            xxx            o ",
    " x!!           o            X                      xx  xxx",
    " x!!=          o           xxx                        !x x",
    " x!!          xxx         xx!xx              xx      !!x x",
    " x!!   c                 xx!!!xx      xx             !!x x",
    " x!!!                   xx!!!!!xx                  =!!!x x",
    " x!!!!    o        x    xx!!!!!xx   c       xxxx   !!!!x x",
    " x!!!!!   x             xxvxvxvxx                 !!!!!x x",
    " x!!!!!                                          =!!!!!x x",
    " x!!!!!!!     xx        xx         o     xx     !!!!!!!x x",
    " x!!!!!!!                        o              !!!!!!!x x",
    " x!!!!!!!!!                     xxxx          !!!!!!!!!x x",
    " x!!!!!!!!!=     c                           =!!!!!!!!!x x",
    " x!!!!!!!!!!!      xxxx              x      !!!!!!!!!!!x x",
    " x!!!!!!!!!!!!                             !!!!!!!!!!!!x x",
    " x!!!!!!!!!!!!!!!             xx        !!!!!!!!!!!!!!!x x",
    " x!!!!!!!!!!!!!!!!!!                 !!!!!!!!!!!!!!!!!!x x",
    " x!!!!!!!!!!!!!!!!!!!!!xx   @     !!!!!!!!!!!!!!!!!!!!!x x",
    " x!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!x x",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx x"],
    ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
     "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
     "                                   ",
     " x   x  x       x x xx    x x      ",
     " x   x  x       x x xxx   x x      ",
     " x   x  x       x x x xx  x x      ",
     " x   x  x   x   x x x  xx x x      ",
     " xx xx  xx xxx xx x x   xxx        ",
     "  xxx    xxx xxx  x x    xx x      ",
     "                                   ",
     "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
